### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cxin-william** [kirin123kirin/pytsql#2]
Traceback (most recent call last):
  File "C:/Users/chengxin/PycharmProjects/HD_BigData/utils_all.py", line 112, in <module>
    import pytsql
  File "C:\Users\chengxin\streaming\lib\site-packages\pytsql\__init__.py", line 2, in <module>
    from .TSqlParser import TSqlParser
  File "C:\Users\chengxin\streaming\lib\site-packages\pytsql\TSqlParser.py", line 6835, in <module>
    class TSqlParser ( Parser ):
NameError: name 'Parser' is not defined

**Comment by kirin123kirin** [comment]
Have you finished installing antl4?

```
pip install antlr4-python3-runtime==4.7.2
```

**Comment by cxin-william** [comment]
`select uuid,filler,fildate,lastmodifyoper,lstupdtime,promotionid,promotionname,promotionamount,favamountchannel,favamountmerchant,favamountothers,productid,productquantity,productprice,productfavouramount,oca,tenantid,orderuuid,promotiontype,promotionmemo,pcsAmountBuyer,pcsAmountMerchant,pcsAmountChannel,promotionactivityid,promotionscope,productmemo,productfavamountmerchant,productfavamountchannel,productfavamountothers,source, 'pay_hnhg' etl_db_source from pay_hnhg.cppayorderpromotion`

result：['PROMOTIONID',
 'SOURCE',
 'LSTUPDTIME',
 'PROMOTIONNAME',
 'PRODUCTID',
 'PCSAMOUNTCHANNEL',
 'FAVAMOUNTOTHERS',
 'PROMOTIONMEMO',
 'PRODUCTFAVOURAMOUNT',
 'PRODUCTMEMO',
 'OCA',
 'PROMOTIONACTIVITYID',
 'LASTMODIFYOPER',
 'FAVAMOUNTCHANNEL',
 'UUID',
 'PROMOTIONSCOPE',
 'PRODUCTQUANTITY',
 'FILDATE',
 'PRODUCTFAVAMOUNTOTHERS',
 'ORDERUUID',
 'PCSAMOUNTMERCHANT',
 'PRODUCTFAVAMOUNTMERCHANT',
 'FILLER',
 'FAVAMOUNTMERCHANT',
 'PROMOTIONAMOUNT',
 'PRODUCTPRICE',
 'PROMOTIONTYPE',
 'PCSAMOUNTBUYER',
 'PRODUCTFAVAMOUNTCHANNEL',
 'TENANTID']

There is no etl_db_source，another problem is that it's case insensitive
